Add missing connectLogger @types/express
log4js-node/log4js-node pull request #1393
Opened 2023-09-02 20:53 UTC by xseman

Thanks for the great library!

In my recent project, I noticed a way to enhance `connectLogger` typings. By adding `@types/express` to replace the current `any` return type, I aim to improve its robustness.

2024-05-17 05:18 UTC, xseman commented
@lamweili Could you please provide some feedback? Thank you!

2024-07-18 05:17 UTC, lamweili requested changes

2024-07-18 05:17 UTC, lamweili commented on types/log4js.d.ts
> +): express.Handler
Just for consistency with line 21, the trailing semi-colon should be there.
```suggestion
): express.Handler;
```

2024-07-25 08:44 UTC, xseman commented
The npm install command does not include peerDependencies if they are marked as optional in peerDependenciesMeta. 
To resolve issues with the `tsc -p check`, i can add a step to your workflow to install these optional types.

2024-07-25 11:15 UTC, lamweili commented
Yes please. Thanks!

2024-10-05 07:03 UTC, xseman commented
@lamweili, let me know if there's anything else I can do to close this merge request.

2026-04-12 06:43 UTC, xseman commented
Hi @lamweili, is this ready for review?

2026-06-20 18:21 UTC, xseman commented on .github/workflows/node.js.yml
> +
Fixed in 6f4dfaa.

Switched to `npm install --no-save @types/express`. `--save-peer` was added in npm 7, but this workflow's matrix runs npm 5.x/6.x on Node 8–14, where the flag is unsupported and would fail the job. `--no-save` works across all npm versions and makes the Express types available for the `npm run typings` step without modifying `package.json` or `package-lock.json`.

2026-06-20 18:21 UTC, xseman commented on package.json
>    "browser": {
Leaving the optional peer dependency in place — the premise here doesn't hold for this PR.

The comment assumes the typings use a structural `ConnectLoggerHandler` type and no longer depend on `@types/express`. They do depend on it: `types/log4js.d.ts` imports `express` and returns `express.Handler` (lines 3, 21 and 46) — which is also the form requested in review. Given that, the `peerDependencies` + `peerDependenciesMeta` entries are meaningful: they advertise the types required for the typed `connectLogger` return while keeping them optional for consumers who don't use it.

(The unrelated `package-lock.json` churn noted in the review overview — including the invalid `react-devtools-core` `version` field — was reverted separately in 1c6fa1e, since an optional peer dependency isn't recorded in a lockfileVersion 1 lockfile.)

2026-06-20 18:41 UTC, xseman commented on package.json
>    "browser": {
Update — dropping the peer dependency after all, in e8c3f4b, though for a different reason than originally stated.

The typings genuinely use `express.Handler` (so the original premise about a structural type didn't apply), and that return type is being kept. But the optional `peerDependencies` declaration turned out to break the typings check on npm 11 (Node 24/26): with `@types/express` declared as an *optional peer*, `npm install --no-save @types/express` is treated as already-satisfied and skips installing it, so `tsc` fails with `Cannot find module 'express'`. Verified locally against npm 11 — removing the declaration makes the install place the types correctly ("added 12 packages" vs "added 3 packages", present vs absent).

So: `connectLogger` still returns `express.Handler`; CI installs `@types/express` via `--no-save` purely for the typecheck; the peer-dep block is removed.

2026-06-21 05:03 UTC, lamweili commented
Interesting to see two AIs crossing swords!

2026-06-21 07:33 UTC, xseman commented
> Interesting to see two AIs crossing swords!

Yeah, that was quite an experiment

2026-06-21 11:49 UTC, merged